load("@build_bazel_rules_swift//swift:swift.bzl", "swift_test")

swift_test(
    name = "XCTestDynamicOverlayTests",
    srcs = glob(["XCTestDynamicOverlayTests/*.swift"]),
    module_name = "XCTestDynamicOverlayTests",
    deps = [
        "//:XCTestDynamicOverlay",
    ],
)
